version: '3.1'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_DATABASE="twoots"
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db:rw

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    ports:
      - 8081:8081

# version: '3.1'

# services:

#   mongo:
#     container_name: mongo
#     image: mongo:latest
#     restart: always
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=root
#       - MONGO_INITDB_ROOT_PASSWORD=example
#     ports:
#       - 27017:27017
#     volumes:
#       - ./db:/data/db:rw

#   mongo-express:
#     container_name: mongo-express
#     image: mongo-express
#     environment:
#       - ME_CONFIG_MONGODB_SERVER: mongo
#       - ME_CONFIG_MONGODB_PORT: 27017
#       - ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       - ME_CONFIG_ADMINPASSWORD: example
#       - ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

#     depends_on:
#       - mongo
#     ports:
#       - 8081:8081
